name: ts_logger
description: "A package intended for logging API requests and responses in debug console in a simple way."
version: 1.1.0
repository: "https://github.com/Tim-Solution/ts-flutter-packages/tree/main/pkgs/ts_logger"
platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
